### ISSUE TITLE
Forgot to define Function.identity?

### ISSUE THREAD

**Issue by SamB** [js-choi/proposal-function-pipe-flow#2]
> If `Function.flow` receives no arguments, then, by default, it will return `Function.identity` (which is defined later in this proposal).

But the word identity isn't found anywhere else in the README. I can't take this kind of suspense! ;-)

**Comment by js-choi** [comment]
My apologies for the confusion. This is an out-of-date sentence left over from the previous version of this proposal, [proposal-function-helpers](https://github.com/tc39/proposal-function-helpers/), which bundled together a bunch of helper functions included Function.pipe, Function.flow, and Function.identity. [In October, proposal-function-helpers](https://github.com/tc39/proposal-function-helpers/issues/17#issuecomment-953814353) was rejected for being too broad, so I split it up into two smaller proposals. 

The intent is that, when given no arguments, Function.flow would return an identity function, but there is no actual Function.identity function in this proposal. I currently am not pursuing a Function.identity proposal, although I might in the future.

I will fix this typo when I can.
